name: Happy new year!

on:
  schedule:
    - cron: '0 15 31 12 *' # JST
  workflow_dispatch:

env:
  TZ: Asia/Tokyo

jobs:
  greeting:
    runs-on: ubuntu-latest

    steps:
      - name: Run greeting
        run: year=$(date | awk '{print $NF}') && echo 'Happy new year! '$year
